"""Repository ingestion and indexing for the evidence-first v2 pipeline."""

from __future__ import annotations

import ast
import hashlib
import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence

from app.analysis.evidence import EvidenceItem


SKIP_DIR_NAMES = frozenset(
    {
        ".git",
        ".code_index",
        "__pycache__",
        "venv",
        ".venv",
        "env",
        ".mypy_cache",
        ".pytest_cache",
        "node_modules",
        "dist",
        "build",
        ".ruff_cache",
        # Static-site and framework build outputs — never source.
        "_site",
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".sapper",
        "__sapper__",
        "out",
        ".cache",
        ".parcel-cache",
        ".turbo",
        "coverage",
        ".nyc_output",
        "vendor",
        # Evaluation / report outputs generated by this tool.
        "reports",
        "evaluation_results",
    }
)

SEARCHABLE_EXTENSIONS = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".mjs",
    ".cjs",
    ".html",
    ".htm",
    ".njk",
    ".md",
    ".rst",
    ".txt",
    ".json",
    ".toml",
    ".yml",
    ".yaml",
    ".css",
    ".ini",
    ".cfg",
}

CONFIG_FILENAMES = {
    "pyproject.toml",
    "requirements.txt",
    "package.json",
    "Dockerfile",
    "docker-compose.yml",
    "wrangler.toml",
    ".env.example",
}

MAX_SOURCE_BYTES = int(os.getenv("MCP_CODE_QNA_MAX_FILE_BYTES", "524288"))
SKIP_FILE_NAMES = {
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
}


@dataclass(frozen=True)
class SourceFile:
    path: str
    rel_path: str
    language: str
    content: str
    lines: List[str]


@dataclass(frozen=True)
class SourceChunk:
    id: str
    file: SourceFile
    chunk_type: str
    start_line: int
    end_line: int
    text: str
    symbol: Optional[str] = None
    metadata: Dict[str, str] = field(default_factory=dict)

    def to_evidence(self, score: float, source: str) -> EvidenceItem:
        return EvidenceItem(
            id=self.id,
            path=self.file.path,
            rel_path=self.file.rel_path,
            start_line=self.start_line,
            end_line=self.end_line,
            evidence_type=self.chunk_type,
            snippet=self.text,
            score=round(float(score), 4),
            source=source,
            symbol=self.symbol,
            language=self.file.language,
            metadata=dict(self.metadata),
        )


def tokenise(text: str) -> List[str]:
    """Tokenize text and split common code identifier conventions."""
    raw_tokens = re.findall(r"[A-Za-z_][A-Za-z0-9_\-\.]*|\d+", text)
    tokens: List[str] = []
    for raw in raw_tokens:
        lowered = raw.lower()
        tokens.append(lowered)
        parts = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", raw)
        parts = re.split(r"[\s_\-\.]+", parts)
        tokens.extend(part.lower() for part in parts if part)
    deduped: List[str] = []
    seen = set()
    for token in tokens:
        if token not in seen:
            deduped.append(token)
            seen.add(token)
    return deduped


def _stable_id(*parts: str) -> str:
    return hashlib.sha1("\0".join(parts).encode("utf-8")).hexdigest()[:16]


def _language_for(path: Path) -> str:
    ext = path.suffix.lower()
    if ext == ".py":
        return "python"
    if ext in {".js", ".jsx", ".mjs", ".cjs"}:
        return "javascript"
    if ext in {".ts", ".tsx"}:
        return "typescript"
    if ext in {".md", ".rst", ".txt"}:
        return "documentation"
    if ext in {".json", ".toml", ".yml", ".yaml", ".ini", ".cfg"}:
        return "configuration"
    if ext in {".html", ".htm", ".njk"}:
        return "template"
    if ext == ".css":
        return "css"
    return "text"


def _line_window(lines: Sequence[str], start: int, end: int, *, before: int = 2, after: int = 2) -> tuple[int, int, str]:
    if not lines:
        return 1, 1, ""
    start_idx = max(0, start - 1 - before)
    end_idx = min(len(lines), end + after)
    return start_idx + 1, end_idx, "\n".join(lines[start_idx:end_idx]).strip()


class RepositoryIndex:
    """In-memory repository index with symbols, chunks, files, and repo map."""

    def __init__(self, repo_path: str) -> None:
        self.repo_path = os.path.abspath(repo_path)
        self.files: List[SourceFile] = []
        self.chunks: List[SourceChunk] = []
        self.symbols: Dict[str, List[SourceChunk]] = {}
        self.repo_map: Dict[str, object] = {}

    def build(self) -> "RepositoryIndex":
        if not os.path.isdir(self.repo_path):
            raise ValueError(f"Repository path {self.repo_path!r} is not a directory")

        for file_path in self._iter_files():
            source = self._read_source_file(file_path)
            if not source:
                continue
            self.files.append(source)
            self.chunks.extend(self._chunk_file(source))

        for chunk in self.chunks:
            if chunk.symbol:
                self.symbols.setdefault(chunk.symbol.lower(), []).append(chunk)

        self.repo_map = self._build_repo_map()
        return self

    def _iter_files(self) -> Iterable[Path]:
        for root, dirs, files in os.walk(self.repo_path):
            dirs[:] = sorted(d for d in dirs if d not in SKIP_DIR_NAMES and not d.startswith("."))
            for name in sorted(files):
                if name in SKIP_FILE_NAMES:
                    continue
                path = Path(root) / name
                if path.name in CONFIG_FILENAMES or path.suffix.lower() in SEARCHABLE_EXTENSIONS:
                    yield path

    def _read_source_file(self, path: Path) -> Optional[SourceFile]:
        try:
            if path.stat().st_size > MAX_SOURCE_BYTES:
                return None
        except OSError:
            return None
        try:
            content = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            return None
        rel_path = os.path.relpath(path, self.repo_path)
        return SourceFile(
            path=str(path),
            rel_path=rel_path,
            language=_language_for(path),
            content=content,
            lines=content.splitlines(),
        )

    def _chunk_file(self, source: SourceFile) -> List[SourceChunk]:
        if source.language == "python":
            chunks = self._chunk_python(source)
            return chunks or [self._whole_file_chunk(source, "file")]
        if source.language in {"javascript", "typescript"}:
            return self._chunk_javascript_like(source) or [self._whole_file_chunk(source, "file")]
        if source.language == "documentation":
            return self._chunk_markdown(source)
        if source.language == "configuration" or Path(source.path).name in CONFIG_FILENAMES:
            return [self._whole_file_chunk(source, "config")]
        return self._sliding_file_chunks(source)

    def _whole_file_chunk(self, source: SourceFile, chunk_type: str) -> SourceChunk:
        end = max(1, len(source.lines))
        text = "\n".join(source.lines[:160]).strip()
        if len(source.lines) > 160:
            text += "\n# ... truncated ..."
        return SourceChunk(
            id=_stable_id(source.rel_path, chunk_type, "1", str(end)),
            file=source,
            chunk_type=chunk_type,
            start_line=1,
            end_line=end,
            text=text,
            metadata={"rel_path": source.rel_path},
        )

    def _chunk_python(self, source: SourceFile) -> List[SourceChunk]:
        try:
            tree = ast.parse(source.content)
        except SyntaxError:
            return []

        chunks: List[SourceChunk] = []
        parents: List[str] = []

        class Visitor(ast.NodeVisitor):
            def visit_ClassDef(self, node: ast.ClassDef) -> None:  # noqa: N802
                # Emit a skeleton chunk for the class: signature + docstring +
                # method stubs. Full method bodies are emitted as separate
                # method chunks so evidence is never duplicated.
                class_line = source.lines[node.lineno - 1]
                parts = [class_line]
                docstring = ast.get_docstring(node)
                if docstring:
                    first = docstring.split(".")[0].strip()
                    parts.append(f'    """{first}."""')
                for item in node.body:
                    if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        stub = source.lines[item.lineno - 1].rstrip()
                        parts.append(f"    {stub.strip()} ...")
                    elif isinstance(item, ast.AnnAssign):
                        # Include dataclass / class-level annotated fields.
                        field_line = source.lines[item.lineno - 1].rstrip()
                        parts.append(f"    {field_line.strip()}")
                text = "\n".join(parts)
                chunks.append(
                    SourceChunk(
                        id=_stable_id(source.rel_path, "class", node.name, str(node.lineno)),
                        file=source,
                        chunk_type="class",
                        start_line=node.lineno,
                        end_line=node.end_lineno or node.lineno,
                        text=text,
                        symbol=node.name,
                        metadata={"parent": ""},
                    )
                )
                parents.append(node.name)
                self.generic_visit(node)
                parents.pop()

            def visit_FunctionDef(self, node: ast.FunctionDef) -> None:  # noqa: N802
                self._emit_method(node)
                self.generic_visit(node)

            def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:  # noqa: N802
                self._emit_method(node)
                self.generic_visit(node)

            def _emit_method(self, node: ast.AST) -> None:
                start = getattr(node, "lineno", 1)
                end = getattr(node, "end_lineno", start)
                # Use exact method boundaries with minimal context bleed.
                window_start, window_end, text = _line_window(
                    source.lines, start, end, before=1, after=1
                )
                name = getattr(node, "name", "")
                chunk_type = "method" if parents else "function"
                chunks.append(
                    SourceChunk(
                        id=_stable_id(source.rel_path, chunk_type, name, str(start), str(end)),
                        file=source,
                        chunk_type=chunk_type,
                        start_line=window_start,
                        end_line=window_end,
                        text=text,
                        symbol=name,
                        metadata={"parent": parents[-1] if parents else ""},
                    )
                )

        Visitor().visit(tree)
        return chunks

    def _chunk_javascript_like(self, source: SourceFile) -> List[SourceChunk]:
        patterns = [
            # Classes
            ("class",    re.compile(r"\bclass\s+([A-Za-z_\$][A-Za-z0-9_\$]*)")),
            # Named function declarations
            ("function", re.compile(r"\b(?:async\s+)?function\s+([A-Za-z_\$][A-Za-z0-9_\$]*)\s*\(")),
            # export function / export async function
            ("function", re.compile(r"\bexport\s+(?:default\s+)?(?:async\s+)?function\s*([A-Za-z_\$][A-Za-z0-9_\$]*)\s*\(")),
            # export default function (anonymous — label as "default")
            ("function", re.compile(r"\bexport\s+default\s+(?:async\s+)?function\s*\(")),
            # Arrow functions: const/let foo = (...) =>
            ("function", re.compile(r"\b(?:export\s+)?(?:const|let|var)\s+([A-Za-z_\$][A-Za-z0-9_\$]*)\s*=\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z_\$][A-Za-z0-9_\$]*)\s*=>")),
            # TypeScript interfaces
            ("class",    re.compile(r"\binterface\s+([A-Za-z_\$][A-Za-z0-9_\$]*)")),
            # TypeScript type aliases
            ("class",    re.compile(r"\btype\s+([A-Za-z_\$][A-Za-z0-9_\$]*)\s*(?:<[^>]*>)?\s*=")),
        ]
        seen_ids: set = set()
        chunks: List[SourceChunk] = []

        for chunk_type, pattern in patterns:
            for match in pattern.finditer(source.content):
                start_line = max(1, source.content[: match.start()].count("\n") + 1)
                # Walk forward to find a reasonable end: look for the closing
                # brace at the same indent level, capped at 120 lines.
                end_line = self._find_block_end(source.lines, start_line, cap=120)
                window_start, window_end, text = _line_window(source.lines, start_line, end_line, before=1, after=1)
                # For anonymous export default, use "default" as the symbol name.
                symbol = match.group(1) if match.lastindex and match.lastindex >= 1 else "default"
                chunk_id = _stable_id(source.rel_path, chunk_type, symbol, str(start_line))
                if chunk_id in seen_ids:
                    continue
                seen_ids.add(chunk_id)
                chunks.append(
                    SourceChunk(
                        id=chunk_id,
                        file=source,
                        chunk_type=chunk_type,
                        start_line=window_start,
                        end_line=window_end,
                        text=text,
                        symbol=symbol,
                    )
                )
        return chunks

    @staticmethod
    def _find_block_end(lines: List[str], start_line: int, *, cap: int = 120) -> int:
        """Estimate where the block starting at start_line ends by brace counting."""
        depth = 0
        found_open = False
        for i, line in enumerate(lines[start_line - 1 : start_line - 1 + cap]):
            depth += line.count("{") - line.count("}")
            if depth > 0:
                found_open = True
            if found_open and depth <= 0:
                return start_line + i
        return min(len(lines), start_line + cap - 1)

    def _chunk_markdown(self, source: SourceFile) -> List[SourceChunk]:
        headings = [idx + 1 for idx, line in enumerate(source.lines) if line.startswith("#")]
        if not headings:
            return [self._whole_file_chunk(source, "documentation")]
        chunks: List[SourceChunk] = []
        boundaries = headings + [len(source.lines) + 1]
        for i, start in enumerate(headings):
            end = boundaries[i + 1] - 1
            title = source.lines[start - 1].lstrip("#").strip() or Path(source.path).name
            text = "\n".join(source.lines[start - 1 : end]).strip()
            chunks.append(
                SourceChunk(
                    id=_stable_id(source.rel_path, "documentation", title, str(start), str(end)),
                    file=source,
                    chunk_type="documentation",
                    start_line=start,
                    end_line=end,
                    text=text,
                    symbol=title,
                )
            )
        return chunks

    def _sliding_file_chunks(self, source: SourceFile) -> List[SourceChunk]:
        if len(source.lines) <= 120:
            return [self._whole_file_chunk(source, "file")]
        chunks: List[SourceChunk] = []
        width = 100
        step = 80
        for start_idx in range(0, len(source.lines), step):
            end_idx = min(len(source.lines), start_idx + width)
            text = "\n".join(source.lines[start_idx:end_idx]).strip()
            if not text:
                continue
            chunks.append(
                SourceChunk(
                    id=_stable_id(source.rel_path, "file", str(start_idx + 1), str(end_idx)),
                    file=source,
                    chunk_type="file",
                    start_line=start_idx + 1,
                    end_line=end_idx,
                    text=text,
                )
            )
        return chunks

    def _build_repo_map(self) -> Dict[str, object]:
        language_counts: Dict[str, int] = {}
        file_types: Dict[str, int] = {}
        for source in self.files:
            language_counts[source.language] = language_counts.get(source.language, 0) + 1
            ext = Path(source.path).suffix.lower() or Path(source.path).name
            file_types[ext] = file_types.get(ext, 0) + 1
        return {
            "repo_path": self.repo_path,
            "file_count": len(self.files),
            "chunk_count": len(self.chunks),
            "symbol_count": sum(len(items) for items in self.symbols.values()),
            "languages": dict(sorted(language_counts.items())),
            "file_types": dict(sorted(file_types.items())),
            "top_level_files": sorted(source.rel_path for source in self.files if "/" not in source.rel_path)[:30],
            "dependencies": self._dependencies(),
        }

    def _dependencies(self) -> List[str]:
        deps: List[str] = []
        for source in self.files:
            name = Path(source.path).name
            try:
                if name == "requirements.txt":
                    for line in source.lines:
                        stripped = line.strip()
                        if stripped and not stripped.startswith("#"):
                            deps.append(stripped)
                elif name == "pyproject.toml":
                    deps.extend(re.findall(r'"([^"]+>=?[^"]*)"', source.content))
                elif name == "package.json":
                    data = json.loads(source.content)
                    for section in ("dependencies", "devDependencies"):
                        deps.extend(f"{dep}@{version}" for dep, version in (data.get(section) or {}).items())
            except Exception:
                continue
        return sorted(set(deps))[:80]
