#!/usr/bin/env python3
"""Generate a tiny Python repository the README and web UI can point at.

Usage:
    python scripts/generate_sample_repo.py /tmp/sample-python-repo
"""

from __future__ import annotations

import argparse
import os
import textwrap
from pathlib import Path

FILES: dict[str, str] = {
    "user_service.py": '''
        """User management and authentication service."""

        from typing import Optional

        from database import Database


        class UserService:
            """Manage user accounts and authentication.

            Wraps a :class:`Database` and exposes a small API for creating, fetching,
            and authenticating users.
            """

            def __init__(self, db: Database) -> None:
                self.db = db

            def create_user(self, username: str, password: str) -> int:
                """Create a new user and return its id."""
                if not username or not password:
                    raise ValueError("username and password are required")
                return self.db.insert("users", {"username": username, "password": password})

            def get_user(self, user_id: int) -> Optional[dict]:
                """Return the user with ``user_id`` or ``None``."""
                return self.db.find_one("users", {"id": user_id})

            def authenticate(self, username: str, password: str) -> bool:
                """Return ``True`` if ``username``/``password`` match a stored user."""
                user = self.db.find_one("users", {"username": username})
                return bool(user and user.get("password") == password)
    ''',
    "order_processor.py": '''
        """Customer order processing service."""

        from dataclasses import dataclass
        from typing import List

        from database import Database


        @dataclass
        class Order:
            order_id: int
            user_id: int
            items: List[str]
            total_cents: int


        class OrderProcessor:
            """Validate and persist orders, and process payment."""

            def __init__(self, db: Database) -> None:
                self.db = db

            def submit_order(self, order: Order) -> int:
                """Persist ``order`` and return the stored row id."""
                if order.total_cents <= 0:
                    raise ValueError("Order total must be positive")
                return self.db.insert("orders", order.__dict__)

            def process_payment(self, order: Order, payment_method: str) -> bool:
                """Charge ``order.total_cents`` using ``payment_method``.

                Args:
                    order: The order to charge for.
                    payment_method: Identifier of the payment method (e.g. "card").

                Returns:
                    ``True`` if the payment succeeded.
                """
                if payment_method not in {"card", "wallet", "bank"}:
                    raise ValueError(f"Unsupported payment method: {payment_method}")
                return True
    ''',
    "database.py": '''
        """Tiny in-memory mock database used by the sample services."""

        from itertools import count
        from typing import Dict, List, Optional


        class Database:
            """A toy in-memory document store keyed by table name."""

            def __init__(self) -> None:
                self._tables: Dict[str, List[dict]] = {}
                self._ids = count(1)

            def insert(self, table: str, row: dict) -> int:
                """Insert ``row`` into ``table`` and return the new id."""
                row = dict(row, id=next(self._ids))
                self._tables.setdefault(table, []).append(row)
                return row["id"]

            def find_one(self, table: str, query: dict) -> Optional[dict]:
                """Return the first row in ``table`` matching ``query``."""
                for row in self._tables.get(table, []):
                    if all(row.get(k) == v for k, v in query.items()):
                        return row
                return None
    ''',
}


def write_repo(target: Path) -> None:
    target.mkdir(parents=True, exist_ok=True)
    for name, body in FILES.items():
        (target / name).write_text(textwrap.dedent(body).lstrip(), encoding="utf-8")
    (target / "README.md").write_text(
        "# sample-python-repo\n\nGenerated by mcp-code-qna's `scripts/generate_sample_repo.py`.\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a tiny sample Python repo.")
    parser.add_argument("target", help="Directory to create (will be made if missing)")
    args = parser.parse_args()
    target = Path(args.target).expanduser().resolve()
    write_repo(target)
    print(f"Wrote {len(FILES) + 1} files to {target}")


if __name__ == "__main__":
    main()
